<a href="https://colab.research.google.com/github/Warspyt/PC_Python_2025II/blob/main/clase__15/Python_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Curso de Programación de Computadores en Python
## Librerías de Python y NumPy
#### Universidad Nacional de Colombia

**Objetivos:**
- Entender qué son las librerías y cómo gestionarlas (estándar y externas).
- Aprender a crear tus propias librerías y paquetes Python.
- Dominar NumPy: arrays, operaciones vectorizadas, broadcasting, álgebra lineal, estadísticas y casos de uso.
- Resolver ejercicios cortos y retos prácticos (incluyen proyectos más grandes).

---

## 📚 Contenido (resumen)
1. Introducción a librerías (qué, por qué, tipos) — con imágenes ilustrativas
2. Instalación y gestión de paquetes (`pip`, `venv`, `requirements.txt`, `conda`)
3. Estructura de módulos y cómo crear una librería propia (package)
4. Buenas prácticas: versionado, documentación, testing básico
5. NumPy profundo: creación, indexing, broadcasting, álgebra lineal, random, performance
6. Ejemplos aplicados y casos de uso (simulación, señales, estadísticas)
7. Ejercicios cortos y retos largos (proyectos)
8. Tips, recursos y pasos siguientes

---
**Nota:**** Este notebook está pensado para ejecutarse en Google Colab o Jupyter. Algunas celdas que instalan paquetes están marcadas y solo deben ejecutarse si es necesario.


## 1️⃣ Introducción a librerías en Python

Una **librería** es un conjunto de módulos que empaquetan funciones, clases y utilidades reutilizables.

Algunas librerias conocidas son:

![Python libraries](https://edteam-media.s3.amazonaws.com/community/original/2ef2016b-1028-43f8-861d-bd8188ea3d5a.jpg)

---

### Tip
> Las librerías populares suelen ofrecer alias estándar: `import numpy as np`, `import pandas as pd`, `import matplotlib.pyplot as plt`.


### 1.1 Librerías de la biblioteca estándar vs externas

- **Estandár (stdlib):** vienen con Python (ej: `math`, `datetime`, `os`, `json`, `csv`). No necesitas instalarlas.
- **Externas:** se instalan desde PyPI (`pip`) o con `conda` (ej: `numpy`, `pandas`, `scipy`, `requests`).

Cuando se empieza un proyecto, se documentan las dependencias en `requirements.txt` o `environment.yml` para `conda`.


In [3]:
# Ejemplo: usar módulos estándar
import math, json, csv, datetime
print('sqrt(16)=', math.sqrt(16))
print('fecha ahora:', datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
print('fecha ahora:', datetime.datetime.now().strftime('%d-%m-%Y %H:%M:%S'))


sqrt(16)= 4.0
fecha ahora: 2025-11-18 19:26:43
fecha ahora: 18-11-2025 19H:26:43


## 2️⃣ Instalación y gestión de paquetes

**pip**:
- `pip install paquete`
- `pip install paquete==1.2.3` para una versión específica

**Entornos virtuales (recomendado):**
- `python -m venv venv` → crear
- `source venv/bin/activate` (Unix) o `venv\Scripts\activate` (Windows)

**requirements.txt**:
- `pip freeze > requirements.txt`
- `pip install -r requirements.txt`

**Conda** (opcional):
- `conda create -n mienv python=3.10`

---

### Ejercicio corto: comprobar pip y crear requirements

Completa la celda para listar la versión de `pip` y (opcional) generar un `requirements.txt` si instala paquetes.


In [5]:
# Opcional: ejecutar en Colab/Jupyter si deseas instalar paquetes (descomentar si hace falta)
# !pip install numpy pandas matplotlib
import sys
import subprocess
print('Python version:', sys.version)
try:
    import pip
    print('pip version:', pip.__version__)
except Exception as e:
    print('pip no disponible:', e)


Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]
pip version: 24.1.2


## 3️⃣ Cómo crear tu propia librería (paquete) en Python

### Estructura mínima de un package:

```
mi_paquete/
├─ mi_paquete/
│  ├─ __init__.py
│  ├─ modulo1.py
│  └─ modulo2.py
├─ tests/
│  └─ test_modulo1.py
└─ setup.py   (opcional para distribución)
```

- `__init__.py` indica que el directorio es un paquete.
- Puedes publicar en PyPI con `twine` o usar `pip install -e .` para desarrollo editable.

### Ejemplo rápido: crear un package dentro del notebook (editable) y usarlo


In [6]:
# Creamos un paquete de ejemplo en el entorno de trabajo (funciona en Colab/Jupyter)
import os
package_root = 'mi_paquete'
if not os.path.exists(package_root):
    os.makedirs(os.path.join(package_root,'mi_paquete'), exist_ok=True)
    os.makedirs(os.path.join(package_root,'tests'), exist_ok=True)

# __init__.py
with open(os.path.join(package_root,'mi_paquete','__init__.py'),'w',encoding='utf-8') as f:
    f.write("from .modulo1 import saludo\n")

# modulo1.py
with open(os.path.join(package_root,'mi_paquete','modulo1.py'),'w',encoding='utf-8') as f:
    f.write('def saludo(nombre):\n')
    f.write('    return f"Hola, {nombre}! Bienvenido a mi_paquete."\n')

# modulo2.py
with open(os.path.join(package_root,'mi_paquete','modulo2.py'),'w',encoding='utf-8') as f:
    f.write('def suma(a,b):\n')
    f.write('    return a+b\n')

print('Estructura creada en', package_root)
print(os.listdir(package_root), '->', os.listdir(os.path.join(package_root,'mi_paquete')))


Estructura creada en mi_paquete
['mi_paquete', 'tests'] -> ['__init__.py', 'modulo2.py', 'modulo1.py']


In [7]:
# Añadimos el paquete al path y probamos su uso
import sys
sys.path.insert(0, 'mi_paquete')
from mi_paquete import saludo
print(saludo('Jay'))


Hola, Jay! Bienvenido a mi_paquete.


### Publicación y distribución (resumen)

- Para distribuir: crear `pyproject.toml` o `setup.py`, build con `python -m build`, subir con `twine upload dist/*`.
- Usa `pip install -e .` durante desarrollo para instalar en modo editable.

---
### Ejercicio: crear módulo propio

Crea un módulo `estadisticas.py` dentro de `mi_paquete` que contenga funciones `promedio(lista)` y `desviacion(lista)`. Luego importa y prueba las funciones.


In [8]:
# Esqueleto: completa el módulo estadisticas.py
mod_path = os.path.join(package_root,'mi_paquete','estadisticas.py')
with open(mod_path,'w',encoding='utf-8') as f:
    f.write('def promedio(xs):\n')
    f.write('    pass\n\n')
    f.write('def desviacion(xs):\n')
    f.write('    pass\n')
print('archivo creado:', mod_path)


archivo creado: mi_paquete/mi_paquete/estadisticas.py


In [9]:
# Solución de referencia (descomentar para usar)
with open(mod_path,'w',encoding='utf-8') as f:
    f.write('import math\n')
    f.write('def promedio(xs):\n')
    f.write('    return sum(xs)/len(xs) if xs else 0\n\n')
    f.write('def desviacion(xs):\n')
    f.write('    m = promedio(xs)\n')
    f.write('    var = sum((x-m)**2 for x in xs)/len(xs) if xs else 0\n')
    f.write('    return math.sqrt(var)\n')

# Probar
sys.path.insert(0, 'mi_paquete')
from mi_paquete.estadisticas import promedio, desviacion
print('promedio [1,2,3]=', promedio([1,2,3]))
print('desviacion [1,2,3]=', desviacion([1,2,3]))


promedio [1,2,3]= 2.0
desviacion [1,2,3]= 0.816496580927726


## 4️⃣ Buenas prácticas: documentación, testing y versionado

- Documenta con docstrings y `README.md`.
- Usa `pytest` para tests básicos (`tests/test_modulo.py`).
- Usa control de versiones (git) y sigue semver para releases.

### Ejercicio corto: escribe un test para `promedio` usando `pytest` (esqueleto)


In [10]:
# Esqueleto test (guardar en mi_paquete/tests/test_estadisticas.py)
test_code = '''
from mi_paquete.estadisticas import promedio

def test_promedio():
    assert promedio([1,2,3]) == 2
'''
with open(os.path.join(package_root,'tests','test_estadisticas.py'),'w',encoding='utf-8') as f:
    f.write(test_code)
print('Test creado:', os.path.join(package_root,'tests','test_estadisticas.py'))


Test creado: mi_paquete/tests/test_estadisticas.py


## 5️⃣ NumPy

En esta sección ampliamos los usos de NumPy: manejo de tipos, broadcasting complejo, álgebra, transformadas rápidas (FFT básica), generación de señales y comparación de rendimiento con listas.


In [16]:
import numpy as np
# Tipos y casting
a = np.array([1,2,3], dtype=np.int32)
print('a dtype:', a.dtype)
print('a as float:', a.astype(float))

# Broadcasting avanzado
M = np.ones((4,3))
print("M",M)
v = np.arange(3)
print("v",v)
print('M+v:\n', M+v)

# Operaciones lógicas y masking
x = np.arange(10)
print(x)
mask = (x % 2 == 0)
print('pares:', x[mask])

x = np.arange(1,11)
print(x)
mask = (x % 2 == 1)
print('pares:', x[(x % 2 == 0)])



a dtype: int32
a as float: [1. 2. 3.]
M [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
v [0 1 2]
M+v:
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[0 1 2 3 4 5 6 7 8 9]
pares: [0 2 4 6 8]
[ 1  2  3  4  5  6  7  8  9 10]
pares: [ 2  4  6  8 10]


### 5.1 Álgebra lineal y aplicaciones
- `np.linalg` para resolver sistemas y calcular autovalores.
- Ejemplo: resolver grandes sistemas y medir tiempo.


In [20]:
# Resolver un sistema y calcular autovalores
A = np.random.rand(5,5)
print("A",A)
b = np.random.rand(5)
print("b",b)
x = np.linalg.solve(A,b)
print("x",x)
vals, vecs = np.linalg.eig(A)
print("vals",vals)
print("vecs",vecs)
print('solución x[:3]=', x[:3])
print('autovalores[:3]=', vals[:3])


A [[0.38073475 0.16971478 0.64569677 0.84478014 0.36678521]
 [0.24840982 0.77298396 0.63162252 0.70401516 0.79820659]
 [0.06899722 0.31678327 0.01678065 0.76979873 0.74508289]
 [0.52433783 0.87452931 0.10663839 0.86271947 0.90296529]
 [0.05913451 0.15776596 0.83814035 0.87149263 0.72563158]]
b [0.23205308 0.03007531 0.08566642 0.50228875 0.2497299 ]
x [ 2.74841581 -1.93373422  0.13664705 -1.76816242  2.50635762]
vals [ 2.78720798+0.j        -0.28771564+0.2260341j -0.28771564-0.2260341j
  0.32414106+0.j         0.22293263+0.j       ]
vecs [[-0.38330469+0.j          0.51465019+0.00057792j  0.51465019-0.00057792j
  -0.80471231+0.j          0.6132613 +0.j        ]
 [-0.51104969+0.j         -0.08536231-0.11661991j -0.08536231+0.11661991j
   0.58025408+0.j         -0.66052074+0.j        ]
 [-0.33407056+0.j         -0.04433301+0.24707631j -0.04433301-0.24707631j
   0.06813827+0.j          0.01418046+0.j        ]
 [-0.55187125+0.j         -0.59253669+0.j         -0.59253669-0.j
  -0.09464358+0

### 5.2 FFT y señales (introducción)
- `np.fft.fft` y `np.fft.ifft` para transformadas rápidas.
- Ejemplo: generar señal con ruido y estimar frecuencia dominante.


In [21]:
import numpy as np
fs = 500  # sample rate
t = np.arange(0,1,1/fs)
sig = np.sin(2*np.pi*50*t) + 0.5*np.random.randn(len(t))
fft = np.fft.fft(sig)
freqs = np.fft.fftfreq(len(sig), 1/fs)
idx = np.argmax(np.abs(fft))
print('Freq dominante (Hz):', abs(freqs[idx]))


Freq dominante (Hz): 50.0


### 5.3 Performance: listas vs NumPy
- Medir tiempos con `%timeit` (en Jupyter) o `time` en scripts.


In [26]:
import time
x = 10_000_00.345_678
print(x)
n = 10_000_000
lst = list(range(n))
start = time.time()
sum_lst = sum([x*x for x in lst])
end = time.time()
dur1 = end-start
print('Lista comprehension time:', dur1)

arr = np.arange(n)
start = time.time()
sum_arr = np.sum(arr*arr)
end = time.time()
dur2 = end-start
print('NumPy vectorized time:', dur2)

print("Factor de", dur1/dur2)


1000000.345678
Lista comprehension time: 0.9804995059967041
NumPy vectorized time: 0.03644680976867676
Factor de 26.902203847738914


# 6️⃣ Ejercicios

### Ejercicio corto A: multiplicar matrices
- Crea dos matrices A (3x3) y B (3x3) con valores aleatorios y calcula A@B y A*B (element-wise).  


In [27]:
# Esqueleto Ejercicio corto A
import numpy as np

def ejercicio_corto_A():
    A = np.array([[1,1],[1,1]])
    B = np.array([[2,2],[2,2]])
    # TODO: crear A,B y calcular
    print("mult matr", A@B)
    print("mult elem", A*B)
    return None

# Descomenta para probar después
print(ejercicio_corto_A())


mult matr [[4 4]
 [4 4]]
mult elem [[2 2]
 [2 2]]
None


In [ ]:
# Solución referencia Ejercicio corto A
import numpy as np

def ejercicio_corto_A():
    A = np.random.rand(3,3)
    B = np.random.rand(3,3)
    matmul = A @ B
    elem = A * B
    return matmul, elem

print(ejercicio_corto_A())


### Ejercicio corto B: máscara y filtrado
- Dado un array de 1000 valores aleatorios normales, cuenta cuántos están entre -1 y 1.


In [ ]:
# Esqueleto Ejercicio corto B
import numpy as np

def ejercicio_corto_B(seed=0):
    # TODO: generar muestras y contar
    return None


In [33]:
# Solución referente Ejercicio corto B
import numpy as np

def ejercicio_corto_B(seed=0):
    np.random.seed(seed)
    s = np.random.randn(1000)
    s2 = np.random.rand(1000)
    print("distrib normal", s[:10])
    print("distrib unifor", s2[:10])
    count = np.sum((s>-1)&(s<1))
    print("count",count)
    return int(count)

print(ejercicio_corto_B(50))


distrib normal [-1.56035211 -0.0309776  -0.62092842 -1.46458049  1.41194612 -0.47673214
 -0.78046921  1.07026774 -1.2822926  -1.3274789 ]
distrib unifor [0.51083964 0.50704439 0.96543271 0.26942947 0.9348027  0.34452594
 0.48127395 0.36071196 0.6563937  0.36189006]
count 684
684


# 7️⃣ Reto — Proyecto 1: Análisis de datos sintéticos

**Descripción:** Genera un dataset sintético (CSV) de mediciones experimentales (por ejemplo, temperatura, presión, tiempo). Luego:
- Lee el CSV con `numpy.genfromtxt` o `pandas` (si lo deseas).
- Calcula estadísticas por columna.
- Aplica filtrado (elimina outliers > 3σ).
- Guarda un archivo limpio y genera un reporte con resultados.

**Requisitos:** manejo de archivos, NumPy, control de errores.


In [ ]:
# Esqueleto proyecto 1: generar CSV, procesar y guardar
import numpy as np
import csv

def generar_dataset(path='datos_sinteticos.csv', n=1000, seed=0):
    np.random.seed(seed)
    tiempo = np.arange(n)
    temperatura = 20 + 2*np.sin(2*np.pi*tiempo/50) + np.random.randn(n)
    presion = 1 + 0.01*np.random.randn(n)
    with open(path,'w',newline='',encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['tiempo','temperatura','presion'])
        for i in range(n):
            writer.writerow([tiempo[i], f"{temperatura[i]:.3f}", f"{presion[i]:.4f}"])
    print('Dataset generado en', path)


def procesar_dataset(path_in='datos_sinteticos.csv', path_out='datos_limpios.csv'):
    # TODO: leer, calcular stats, filtrar outliers y guardar limpio
    pass


In [ ]:
# Solución de referencia (usar para guiarse)
import numpy as np
import csv

def procesar_dataset(path_in='datos_sinteticos.csv', path_out='datos_limpios.csv'):
    data = np.genfromtxt(path_in, delimiter=',', names=True, dtype=float)
    temps = data['temperatura']
    pres = data['presion']
    mean_t, std_t = np.mean(temps), np.std(temps)
    mask = np.abs(temps - mean_t) <= 3*std_t
    clean_idx = np.where(mask)[0]
    with open(path_out,'w',newline='',encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['tiempo','temperatura','presion'])
        for i in clean_idx:
            writer.writerow([int(data['tiempo'][i]), f"{temps[i]:.3f}", f"{pres[i]:.4f}"])
    print('Procesado.Stats: mean_t=', mean_t, 'std_t=', std_t, 'n_clean=', len(clean_idx))


# 8️⃣ Reto — Proyecto 2: Procesamiento de señales

**Descripción:** Simula una señal con varias frecuencias y ruido. Usa FFT para detectar frecuencias dominantes y filtrar ruido (filtro pasa-bajo simple). Guarda la señal original y filtrada en archivos y grafica resultados (si estás en Colab/Jupyter permite `%matplotlib inline`).


In [ ]:
# Esqueleto proyecto 2: señal, FFT y filtrado
import numpy as np
import matplotlib.pyplot as plt

def generar_senal(fs=1000, dur=1.0):
    t = np.arange(0, dur, 1/fs)
    sig = 0.7*np.sin(2*np.pi*50*t) + 0.3*np.sin(2*np.pi*120*t) + 0.5*np.random.randn(len(t))
    return t, sig

def filtrar_pasabajo(sig, fs, cutoff=100):
    # TODO: FFT, cero componentes > cutoff, iFFT
    return None

# Prueba rápida (descomentar después de implementar)
# t, sig = generar_senal()
# tfilt = filtrar_pasabajo(sig, 1000, cutoff=80)


In [ ]:
# Solución referencia proyecto 2 (guía)
import numpy as np
import matplotlib.pyplot as plt

def filtrar_pasabajo(sig, fs, cutoff=100):
    N = len(sig)
    S = np.fft.fft(sig)
    freqs = np.fft.fftfreq(N, 1/fs)
    S_filtered = S.copy()
    S_filtered[np.abs(freqs) > cutoff] = 0
    sig_filt = np.fft.ifft(S_filtered).real
    return sig_filt

# Ejemplo de uso (descomentar en entorno gráfico)
# t, sig = generar_senal()
# sig_f = filtrar_pasabajo(sig, 1000, cutoff=80)
# plt.figure(figsize=(10,4)); plt.plot(t[:500], sig[:500], label='original'); plt.plot(t[:500], sig_f[:500], label='filtrada'); plt.legend(); plt.show()


## ✅ Tips, recomendaciones y recursos finales

- Prefiere entornos virtuales y `requirements.txt` para reproducibilidad.
- Documenta con `README.md` y docstrings; usa `sphinx` para documentación formal.
- Usa `pytest` para tests y CI (GitHub Actions) para automatizar pruebas.
- Aprende a usar `numpy`, `pandas`, `matplotlib`, `scipy` y luego explora `scikit-learn` para ML.

**Recursos:**
- NumPy docs: https://numpy.org/doc/
- Python packaging guide: https://packaging.python.org/
- Tutoriales: Real Python, SciPy lectures
